name: mileager
description: "A vehicle mileage tracking app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  provider: ^6.1.1
  flutter_blue_plus: ^1.31.13
  geolocator: ^10.1.1
  image_picker: ^1.0.7
  image_cropper: ^9.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.4.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  excel: ^4.0.2
  intl: ^0.19.0
  device_info_plus: ^10.1.0
  file_picker: ^8.0.0+1
  path: ^1.8.3
  share_plus: ^7.2.1
  mailer: ^6.0.1
  url_launcher: ^6.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true 